import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import { headers } from "next/headers";
import "@/node_modules/react-modal-video/css/modal-video.css";
import "@/public/assets/css/main.css";
import { LanguageProvider } from "@/util/LanguageContext";

const urbanist = Urbanist({
    weight: ["300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin"],
    variable: "--urbanist",
    display: "swap",
});

export const metadata: Metadata = {
    title: "VING - Car rental Bootstrap 5 Next.js Template",
    description: "Generated by VING - Car rental Bootstrap 5 Next.js Template",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headersList = await headers()
    const locale = headersList.get('x-locale') || 'HU-hu'
    const lang = locale.split('-')[1] // 'hu', 'en', 'de'

    return (
        <html lang={lang}>
            <body className={`${urbanist.variable}`}>
                <LanguageProvider initialLocale={locale}>{children}</LanguageProvider>
            </body>
        </html>
    );
}

